// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlWqfHcRBf8_PgTUq75bQJpefhMGTB9uo',
    appId: '1:581675183074:web:b1a53799316cb08ae2a7bb',
    messagingSenderId: '581675183074',
    projectId: 'inclass13-12faf',
    authDomain: 'inclass13-12faf.firebaseapp.com',
    storageBucket: 'inclass13-12faf.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBosWjTnQdNi4sIi8wUR3j5Uu1C9vQ7T88',
    appId: '1:581675183074:android:ed42cc7bf1459fc8e2a7bb',
    messagingSenderId: '581675183074',
    projectId: 'inclass13-12faf',
    storageBucket: 'inclass13-12faf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJS8rPquMlJfUJgdnkAiWm2vfgx6eRi1I',
    appId: '1:581675183074:ios:43dd08a8c3eadf6de2a7bb',
    messagingSenderId: '581675183074',
    projectId: 'inclass13-12faf',
    storageBucket: 'inclass13-12faf.firebasestorage.app',
    iosBundleId: 'com.example.inclass13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJS8rPquMlJfUJgdnkAiWm2vfgx6eRi1I',
    appId: '1:581675183074:ios:43dd08a8c3eadf6de2a7bb',
    messagingSenderId: '581675183074',
    projectId: 'inclass13-12faf',
    storageBucket: 'inclass13-12faf.firebasestorage.app',
    iosBundleId: 'com.example.inclass13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlWqfHcRBf8_PgTUq75bQJpefhMGTB9uo',
    appId: '1:581675183074:web:9f86a6dc2413877be2a7bb',
    messagingSenderId: '581675183074',
    projectId: 'inclass13-12faf',
    authDomain: 'inclass13-12faf.firebaseapp.com',
    storageBucket: 'inclass13-12faf.firebasestorage.app',
  );
}
